{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.2-dev1/core-0.0.2-dev1.module",
    "group": "com.linroid.ketch",
    "module": "core",
    "version": "0.0.2-dev1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.linroid.ketch",
          "module": "api",
          "version": {
            "requires": "0.0.2-dev1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm.jar",
          "url": "core-jvm-0.0.2-dev1.jar",
          "size": 345402,
          "sha512": "66ab82029fa662f113a3ae797673587575e48e8f5e7012717c5941ad714479d34e515f8e288c6784370e351ae658235b19a19c63d28eb672ea76c65ef4c4b4e3",
          "sha256": "7dc3df57704bae9d4becb2723e11d1dedb3b809716786abcf83fb7c3f6f1e62e",
          "sha1": "d6ba89708145e49cb25b9948b15a6707fa6beaf4",
          "md5": "bc4b0d7330c716553d56b4d27490cbfc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.linroid.ketch",
          "module": "api",
          "version": {
            "requires": "0.0.2-dev1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm.jar",
          "url": "core-jvm-0.0.2-dev1.jar",
          "size": 345402,
          "sha512": "66ab82029fa662f113a3ae797673587575e48e8f5e7012717c5941ad714479d34e515f8e288c6784370e351ae658235b19a19c63d28eb672ea76c65ef4c4b4e3",
          "sha256": "7dc3df57704bae9d4becb2723e11d1dedb3b809716786abcf83fb7c3f6f1e62e",
          "sha1": "d6ba89708145e49cb25b9948b15a6707fa6beaf4",
          "md5": "bc4b0d7330c716553d56b4d27490cbfc"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-sources.jar",
          "url": "core-jvm-0.0.2-dev1-sources.jar",
          "size": 48086,
          "sha512": "98966fd47e38f3697aa3699eac8217fbf7d8e71cd8f3b4d1e20b52026acb55d5caece6173a8fef3f6a3c9c6fd22e2bea22d75b0a92ebe69b2c49d20100f9c888",
          "sha256": "bd286c84bac659be69bc54d570a543ebb93421d6037c7757f3ce5d2c66a8ef94",
          "sha1": "8e9b985176ade24fd672b7537717a87de65b59f3",
          "md5": "1434b343f3b47b99d8d12dc92602c083"
        }
      ]
    }
  ]
}
