{
  "formatVersion": "1.1",
  "component": {
    "group": "com.linroid.ketch",
    "module": "ftp",
    "version": "0.0.2-dev1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.linroid.ketch",
          "module": "core",
          "version": {
            "requires": "0.0.2-dev1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftp-metadata.jar",
          "url": "ftp-0.0.2-dev1.jar",
          "size": 8174,
          "sha512": "20760259299f85b6443e0feb767842d82cb5f504bbf43c087a060444ac955657477a7f5d4f75b7e02609a4e5852bed206f81dea8b049646ed402d1973d41595b",
          "sha256": "e7cbdd169a2b7a42495240e8c9888d91e792b92c1012e7a998ffa0fb8533480e",
          "sha1": "3d7d397a6250b4da0ae7b302596b2ab5dc90a7c9",
          "md5": "65b2cf2a31819d0210cb803919ef2c3c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ftp-kotlin-sources.jar",
          "url": "ftp-0.0.2-dev1-sources.jar",
          "size": 14095,
          "sha512": "c68640b6d8247ac2560ebd39356282692ab49215bde61de51d5da24f7394732f7e38582352fe9b3f04a83bfc402d2e3f81f670c99ee67cb9b11029a430e0ac0c",
          "sha256": "bd690acaf8d8f9895d96d54d286f8dcf906da25795144c6097a60eca15442ac8",
          "sha1": "4cf74d0ccffbc911d788ee12bb4d14661cbe752f",
          "md5": "1850e43d9fc070a6af3e80a27941ec15"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ftp-android/0.0.2-dev1/ftp-android-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "ftp-android",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ftp-android/0.0.2-dev1/ftp-android-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "ftp-android",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ftp-android/0.0.2-dev1/ftp-android-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "ftp-android",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ftp-iosarm64/0.0.2-dev1/ftp-iosarm64-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "ftp-iosarm64",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ftp-iosarm64/0.0.2-dev1/ftp-iosarm64-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "ftp-iosarm64",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ftp-iosarm64/0.0.2-dev1/ftp-iosarm64-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "ftp-iosarm64",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ftp-iossimulatorarm64/0.0.2-dev1/ftp-iossimulatorarm64-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "ftp-iossimulatorarm64",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ftp-iossimulatorarm64/0.0.2-dev1/ftp-iossimulatorarm64-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "ftp-iossimulatorarm64",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ftp-iossimulatorarm64/0.0.2-dev1/ftp-iossimulatorarm64-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "ftp-iossimulatorarm64",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ftp-jvm/0.0.2-dev1/ftp-jvm-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "ftp-jvm",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ftp-jvm/0.0.2-dev1/ftp-jvm-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "ftp-jvm",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ftp-jvm/0.0.2-dev1/ftp-jvm-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "ftp-jvm",
        "version": "0.0.2-dev1"
      }
    }
  ]
}
