{
  "formatVersion": "1.1",
  "component": {
    "group": "com.linroid.ketch",
    "module": "kermit",
    "version": "0.0.2-dev1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.linroid.ketch",
          "module": "api",
          "version": {
            "requires": "0.0.2-dev1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kermit-metadata.jar",
          "url": "kermit-0.0.2-dev1.jar",
          "size": 2532,
          "sha512": "573378dde3ec5b673d160619d734a9276361e21b3181c769f3986102a1794aa9f21a7bc4a34610c02dea814adc0f3e2ffe85a638e86e1eee30479ad6a5d31e5e",
          "sha256": "32e68410e804a41be282d3ca715767406e839243d79fc86ef7541fd522a0bccd",
          "sha1": "c8ac37f4b98cdab6769564a97650f2377833c197",
          "md5": "273ca0f2e702172e7bb547efb387e6b9"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kermit-kotlin-sources.jar",
          "url": "kermit-0.0.2-dev1-sources.jar",
          "size": 1641,
          "sha512": "47857e2e910086d5f34c67480a88931c96b915b7fedb63745752240fa09fd6c62674ab51ec3456d938238ad84242ab639e80bd372b74ccd18bd241e21c6cfac5",
          "sha256": "6ffccf89156db097847a1a1139c72ed36e9e2e2789668e5b668ce1232869aed9",
          "sha1": "64ccf18071ed8fcf39121d9929f64df6405d1c27",
          "md5": "6da6511d5a6135094fabe7ba15b88977"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kermit-android/0.0.2-dev1/kermit-android-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "kermit-android",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kermit-android/0.0.2-dev1/kermit-android-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "kermit-android",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kermit-android/0.0.2-dev1/kermit-android-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "kermit-android",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kermit-iosarm64/0.0.2-dev1/kermit-iosarm64-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "kermit-iosarm64",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kermit-iosarm64/0.0.2-dev1/kermit-iosarm64-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "kermit-iosarm64",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kermit-iosarm64/0.0.2-dev1/kermit-iosarm64-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "kermit-iosarm64",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kermit-iossimulatorarm64/0.0.2-dev1/kermit-iossimulatorarm64-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "kermit-iossimulatorarm64",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kermit-iossimulatorarm64/0.0.2-dev1/kermit-iossimulatorarm64-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "kermit-iossimulatorarm64",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kermit-iossimulatorarm64/0.0.2-dev1/kermit-iossimulatorarm64-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "kermit-iossimulatorarm64",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kermit-js/0.0.2-dev1/kermit-js-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "kermit-js",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kermit-js/0.0.2-dev1/kermit-js-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "kermit-js",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kermit-js/0.0.2-dev1/kermit-js-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "kermit-js",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kermit-jvm/0.0.2-dev1/kermit-jvm-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "kermit-jvm",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kermit-jvm/0.0.2-dev1/kermit-jvm-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "kermit-jvm",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kermit-jvm/0.0.2-dev1/kermit-jvm-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "kermit-jvm",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kermit-wasm-js/0.0.2-dev1/kermit-wasm-js-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "kermit-wasm-js",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kermit-wasm-js/0.0.2-dev1/kermit-wasm-js-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "kermit-wasm-js",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kermit-wasm-js/0.0.2-dev1/kermit-wasm-js-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "kermit-wasm-js",
        "version": "0.0.2-dev1"
      }
    }
  ]
}
