{
  "formatVersion": "1.1",
  "component": {
    "url": "../../torrent/0.0.2-dev1/torrent-0.0.2-dev1.module",
    "group": "com.linroid.ketch",
    "module": "torrent",
    "version": "0.0.2-dev1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.linroid.ketch",
          "module": "core",
          "version": {
            "requires": "0.0.2-dev1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "torrent-iosArm64Main.klib",
          "url": "torrent-iosarm64-0.0.2-dev1.klib",
          "size": 81555,
          "sha512": "989b0d82e1a6e383a4eeae0e8586eb946ee7a24eedb2c77527bf322b139ab56d2de43fffcba7063e0b3d5439d5416aef187567a86f9d5d5c3b08aa5d53f6277b",
          "sha256": "ab49089e5c9ee503dc3526ddc6f3594d0ea7b7c57697b2c7c6871b17f0693e75",
          "sha1": "7abdc5337cac425196bd3acf13bfabd0bd051589",
          "md5": "ee00610e149f1b81f1d61a453e2c7533"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "torrent-iosarm64-sources.jar",
          "url": "torrent-iosarm64-0.0.2-dev1-sources.jar",
          "size": 15776,
          "sha512": "dae5e897d90dbe788ee383fd0b6bbcd3fa01c1c25e5d4ad04b4420175a264f97eca65817c57412320c1357b896ddbc2c1ba605dddf081c65b9d29f8298595d4a",
          "sha256": "f4fa932304ce58db22ffc9be8b9a29975d5588aea1481e4be472113ca95d04c5",
          "sha1": "2faf2441be973770204959c11e3f925961e1ab6c",
          "md5": "af6b3f1134e5035de124d8067a22571b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.linroid.ketch",
          "module": "core",
          "version": {
            "requires": "0.0.2-dev1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "torrent-iosarm64-metadata.jar",
          "url": "torrent-iosarm64-0.0.2-dev1-metadata.jar",
          "size": 2837,
          "sha512": "960427d4fe87eb135dc6e90a16802993306bac7aacc2baf7a84966a45acdba2a9852da14d7ed6379765805f520d9c95c943e2d16e3481b1ec8560fbce7e822ec",
          "sha256": "591d003586d0bcc5beaeb7ebf41041d34ab91a74fcf6622f371d21ba573b2e31",
          "sha1": "c8d4822c2ca3ad80d9aa5c73563f029ce1d28014",
          "md5": "121fcae4b0305185f067b2583468757f"
        }
      ]
    }
  ]
}
