{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor/0.0.2-dev1/ktor-0.0.2-dev1.module",
    "group": "com.linroid.ketch",
    "module": "ktor",
    "version": "0.0.2-dev1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.linroid.ketch",
          "module": "core",
          "version": {
            "requires": "0.0.2-dev1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-jvm.jar",
          "url": "ktor-jvm-0.0.2-dev1.jar",
          "size": 18905,
          "sha512": "27c3f609b73ace60ccdbb3bae35e0a71d8191722b5efb7caa3f6431045edb0a33ef95ff66ac9e00453c272d8756d77fcbfd9fff54c1f39ac55c284a7726325be",
          "sha256": "041f99a7e5d18012e695ea75db932a40f6519eb3616ec879d0f7c4523897206e",
          "sha1": "56542a57a6df36739664d6092a981ba84600584c",
          "md5": "78d51d00265a3c80326abcd6e3df7475"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.linroid.ketch",
          "module": "core",
          "version": {
            "requires": "0.0.2-dev1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-jvm.jar",
          "url": "ktor-jvm-0.0.2-dev1.jar",
          "size": 18905,
          "sha512": "27c3f609b73ace60ccdbb3bae35e0a71d8191722b5efb7caa3f6431045edb0a33ef95ff66ac9e00453c272d8756d77fcbfd9fff54c1f39ac55c284a7726325be",
          "sha256": "041f99a7e5d18012e695ea75db932a40f6519eb3616ec879d0f7c4523897206e",
          "sha1": "56542a57a6df36739664d6092a981ba84600584c",
          "md5": "78d51d00265a3c80326abcd6e3df7475"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-jvm-sources.jar",
          "url": "ktor-jvm-0.0.2-dev1-sources.jar",
          "size": 3414,
          "sha512": "7b64db8f7c48de2b70cb98b70be9c0c2738ca722fbdc83542e8a69d0669b589330db9e0b9713e109a5c04825d52d91661129df19e23b5b71c8e0a5c4d83000fc",
          "sha256": "4a0e2faa6a73bf72d4eea9205c7fa48c23388e63e2e32581863ca6126e2bb63d",
          "sha1": "e6519fe780719ac08f0c43ef9a2559b0efa8e186",
          "md5": "ca642a10ffaa69ed44b02f955e29330d"
        }
      ]
    }
  ]
}
