{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor/0.0.2-dev1/ktor-0.0.2-dev1.module",
    "group": "com.linroid.ketch",
    "module": "ktor",
    "version": "0.0.2-dev1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.linroid.ketch",
          "module": "core",
          "version": {
            "requires": "0.0.2-dev1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-iosArm64Main.klib",
          "url": "ktor-iosarm64-0.0.2-dev1.klib",
          "size": 19120,
          "sha512": "061e0c6294942a4b4490f12b53f7c580386a0f773e68105115a6f228b5c8ba0b0f5f270e5e6cd344d81a3dea096a1577b8e04ced8f65252bc4944d4f4156e53a",
          "sha256": "9d6a958b6735426ae91c3a1cf1208d62ba02863cfd00b6fe8dc4215f4e5336d0",
          "sha1": "dca85e12c52c71adb7fd467684c9533d0a181f12",
          "md5": "419a10a861febbc8dbc1689535e47c35"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-iosarm64-sources.jar",
          "url": "ktor-iosarm64-0.0.2-dev1-sources.jar",
          "size": 3414,
          "sha512": "7b64db8f7c48de2b70cb98b70be9c0c2738ca722fbdc83542e8a69d0669b589330db9e0b9713e109a5c04825d52d91661129df19e23b5b71c8e0a5c4d83000fc",
          "sha256": "4a0e2faa6a73bf72d4eea9205c7fa48c23388e63e2e32581863ca6126e2bb63d",
          "sha1": "e6519fe780719ac08f0c43ef9a2559b0efa8e186",
          "md5": "ca642a10ffaa69ed44b02f955e29330d"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.linroid.ketch",
          "module": "core",
          "version": {
            "requires": "0.0.2-dev1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-iosarm64-metadata.jar",
          "url": "ktor-iosarm64-0.0.2-dev1-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
