{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kermit/0.0.2-dev1/kermit-0.0.2-dev1.module",
    "group": "com.linroid.ketch",
    "module": "kermit",
    "version": "0.0.2-dev1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.linroid.ketch",
          "module": "api",
          "version": {
            "requires": "0.0.2-dev1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kermit-jvm.jar",
          "url": "kermit-jvm-0.0.2-dev1.jar",
          "size": 3499,
          "sha512": "8ab314c59f436c1d4b39fde07adba42e2668237f746085302a6b925c7ce84e1d9c3f31534422290af1c7a4d036080d265b3a400ae06aa39c5da7782da32ab2ae",
          "sha256": "5ba51e2bc20a5ac817bc91d5bad23372d674822e46473a42f5d1eb4b2bc44705",
          "sha1": "71e62de9982d0190d668cb2e47e1d0b55fb580d2",
          "md5": "053ac0bf034b0b14f1f27503a7c52d7d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.linroid.ketch",
          "module": "api",
          "version": {
            "requires": "0.0.2-dev1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kermit-jvm.jar",
          "url": "kermit-jvm-0.0.2-dev1.jar",
          "size": 3499,
          "sha512": "8ab314c59f436c1d4b39fde07adba42e2668237f746085302a6b925c7ce84e1d9c3f31534422290af1c7a4d036080d265b3a400ae06aa39c5da7782da32ab2ae",
          "sha256": "5ba51e2bc20a5ac817bc91d5bad23372d674822e46473a42f5d1eb4b2bc44705",
          "sha1": "71e62de9982d0190d668cb2e47e1d0b55fb580d2",
          "md5": "053ac0bf034b0b14f1f27503a7c52d7d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kermit-jvm-sources.jar",
          "url": "kermit-jvm-0.0.2-dev1-sources.jar",
          "size": 1641,
          "sha512": "47857e2e910086d5f34c67480a88931c96b915b7fedb63745752240fa09fd6c62674ab51ec3456d938238ad84242ab639e80bd372b74ccd18bd241e21c6cfac5",
          "sha256": "6ffccf89156db097847a1a1139c72ed36e9e2e2789668e5b668ce1232869aed9",
          "sha1": "64ccf18071ed8fcf39121d9929f64df6405d1c27",
          "md5": "6da6511d5a6135094fabe7ba15b88977"
        }
      ]
    }
  ]
}
