{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor/0.0.2-dev1/ktor-0.0.2-dev1.module",
    "group": "com.linroid.ketch",
    "module": "ktor",
    "version": "0.0.2-dev1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.linroid.ketch",
          "module": "core",
          "version": {
            "requires": "0.0.2-dev1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-iosSimulatorArm64Main.klib",
          "url": "ktor-iossimulatorarm64-0.0.2-dev1.klib",
          "size": 19187,
          "sha512": "2166c39359fae630ac4060686f92722fb0844ce0c5b2d5e20cc0c44945c1025951cf2211036e5ecce3812006e957c1ab610f112c3b02dac1137210571306c25f",
          "sha256": "d905a48acb7a0a18a315aa664c598ed7f7d4fec193cf0755f801aac88c35b2e3",
          "sha1": "99b767b30d4f53ed6e505b38948c1f3c08acd0b0",
          "md5": "0d03be194388b58ea64c2f4c1197c00e"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-iossimulatorarm64-sources.jar",
          "url": "ktor-iossimulatorarm64-0.0.2-dev1-sources.jar",
          "size": 3414,
          "sha512": "7b64db8f7c48de2b70cb98b70be9c0c2738ca722fbdc83542e8a69d0669b589330db9e0b9713e109a5c04825d52d91661129df19e23b5b71c8e0a5c4d83000fc",
          "sha256": "4a0e2faa6a73bf72d4eea9205c7fa48c23388e63e2e32581863ca6126e2bb63d",
          "sha1": "e6519fe780719ac08f0c43ef9a2559b0efa8e186",
          "md5": "ca642a10ffaa69ed44b02f955e29330d"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.linroid.ketch",
          "module": "core",
          "version": {
            "requires": "0.0.2-dev1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-iossimulatorarm64-metadata.jar",
          "url": "ktor-iossimulatorarm64-0.0.2-dev1-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
