{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.2-dev1/core-0.0.2-dev1.module",
    "group": "com.linroid.ketch",
    "module": "core",
    "version": "0.0.2-dev1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.linroid.ketch",
          "module": "api",
          "version": {
            "requires": "0.0.2-dev1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosSimulatorArm64Main.klib",
          "url": "core-iossimulatorarm64-0.0.2-dev1.klib",
          "size": 218758,
          "sha512": "241fd70b555652befad5718ba0af2d1e0d8b80266805808fc794c2795df05c0a3eeb337f58ef056b880ff43a87ca00bcb26d371b552c4bc956824ba94480adce",
          "sha256": "abca63435a8409f3f19cc648e6fee1615d202d9df5701c60a65d3d5c190335fe",
          "sha1": "de634d5132432e7725d6718cc19f0f901428bf62",
          "md5": "c53f2e2933d1b27af8fe2ae012ae50ae"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iossimulatorarm64-sources.jar",
          "url": "core-iossimulatorarm64-0.0.2-dev1-sources.jar",
          "size": 48245,
          "sha512": "8692612f172d7396ce1040674754d10bc81dd6946cdf6846e0b8733e7134cbe6744def129924a7ee3e27b9dcc2a3b91b93c22736789b8a4191df4f7576276b07",
          "sha256": "e03e5b2bc1213c522564095d73ad545b92352ffb1131b047263f85b0274d97de",
          "sha1": "e0c34a0fb57cc3d13b5899fad7e30e11699c64f3",
          "md5": "49fcfea5fcca38a59b2d9b51b387915c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.linroid.ketch",
          "module": "api",
          "version": {
            "requires": "0.0.2-dev1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-metadata.jar",
          "url": "core-iossimulatorarm64-0.0.2-dev1-metadata.jar",
          "size": 4236,
          "sha512": "78a5249cabe26e965581a81fd119986920620c07fad6c0d6f7d1b8f462737ea8dfc584fd921f19603ea5ff63b1a4cd4b6a744723b9c6203fcac3d24929a59073",
          "sha256": "f261d78b9e755ac9825ba30e54e7e716db32b9b353b08657cef03d098b99b8f0",
          "sha1": "477b636ed02128940d7b33e64fde49bc157b48bd",
          "md5": "57aaf28f7b083384771b58efc6d20b6e"
        }
      ]
    }
  ]
}
