{
  "formatVersion": "1.1",
  "component": {
    "group": "com.linroid.ketch",
    "module": "core",
    "version": "0.0.2-dev1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.linroid.ketch",
          "module": "api",
          "version": {
            "requires": "0.0.2-dev1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata.jar",
          "url": "core-0.0.2-dev1.jar",
          "size": 31526,
          "sha512": "a7c4b4b4afc9b613e89834601ede4389a605e16de84360ad42840d5768c8111b345778ed0fbd60bb339220c83aac6f93533aabd516b0f0f993bd984a174455f9",
          "sha256": "208b732748db549e8c75840cc83d7cdd73c450767f5b173dd7bb0d5820ccca13",
          "sha1": "b872d499dc31b8cb0c9befaca826f95dd47130ac",
          "md5": "eacb5ee6618290955f9037803666dba7"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "core-kotlin-sources.jar",
          "url": "core-0.0.2-dev1-sources.jar",
          "size": 48245,
          "sha512": "84b596d75208e038766ac3518fc4f7c48419f528c6ce2b8ea0ac4430c4418751381e855c3c2b2011fe8ef5a88a310600ea1f69ea85091ad5e5f2c7e690171feb",
          "sha256": "2d78c06448972d9af577ead3c73049eaf63f38db8d22076b86d5580298defd66",
          "sha1": "152b943689197a27457fc46ed3ebc52453c5456b",
          "md5": "dcc78a6134b854b8b7c5ac69f49ccdc4"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.0.2-dev1/core-android-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "core-android",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.0.2-dev1/core-android-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "core-android",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.0.2-dev1/core-android-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "core-android",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/0.0.2-dev1/core-iosarm64-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "core-iosarm64",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/0.0.2-dev1/core-iosarm64-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "core-iosarm64",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/0.0.2-dev1/core-iosarm64-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "core-iosarm64",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.0.2-dev1/core-iossimulatorarm64-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "core-iossimulatorarm64",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.0.2-dev1/core-iossimulatorarm64-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "core-iossimulatorarm64",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.0.2-dev1/core-iossimulatorarm64-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "core-iossimulatorarm64",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/0.0.2-dev1/core-js-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "core-js",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/0.0.2-dev1/core-js-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "core-js",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/0.0.2-dev1/core-js-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "core-js",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.0.2-dev1/core-jvm-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "core-jvm",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.0.2-dev1/core-jvm-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "core-jvm",
        "version": "0.0.2-dev1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.0.2-dev1/core-jvm-0.0.2-dev1.module",
        "group": "com.linroid.ketch",
        "module": "core-jvm",
        "version": "0.0.2-dev1"
      }
    }
  ]
}
